project_id = "hnsgpdsyfyplzksavprv"

[functions.steadfast-courier]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.manage-capi-token]
verify_jwt = false

[functions.manage-users]
verify_jwt = false